Implement a test to ensure linking is done correctly.
newAM/libftd2xx-ffi-rs pull request #9
Opened 2020-12-29 20:39 UTC by Grinkers

On Linux, this project can compile and accidentally add in x86_64 code into an archive that's supposed to be only 32 bit code (version 0.4.0 and earlier). The problem was only detected when trying to link. This test should force linking to occur as it needs to compile and link to run.

On Windows, because things are being dynamically linked, it's more tricky to test. However in practice, it accidentally worked with 32 bit dlls in the correct path.

2020-12-29 21:39 UTC, newAM requested changes
Looks good, made a few suggested changes.

> On Windows, because things are being dynamically linked, it's more tricky to test. However in practice, it accidentally worked with 32 bit dlls in the correct path.

Windows is a bit of a pain, yeah :/

I have a branch that can statically link on Windows, but then it requires *other* libraries that are very out of date (they do not ship with Windows anymore), and I cannot redistribute those.  Then the legacy libraries also export some symbols which can cause name clash with other common libraries and it quickly spirals into a giant mess.

2020-12-29 21:39 UTC, newAM commented on tests/lib.rs
> +extern crate libftd2xx_ffi;
```suggestion
```

`extern crate` is not needed anymore: https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html

2020-12-29 21:39 UTC, newAM commented on tests/lib.rs
> +use libftd2xx_ffi::*;
```suggestion
use libftd2xx_ffi::FT_GetLibraryVersion;
```

A direct import is more clear here.

2020-12-29 21:39 UTC, newAM commented on tests/lib.rs
> +    unsafe {
This returns a status value that should be checked as well.
```suggestion
    let status = unsafe {
```

Then with the other assert
```rust
assert_eq!(status, 0);
```

2020-12-29 22:00 UTC, Grinkers commented
Updated.

2020-12-29 22:21 UTC, Grinkers commented
Regarding Windows, I suspect it's a pain.

In my project, originally all C, I can use the msvc flag /MD with the supplied .lib files and everything gets compiled into one blob.
https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=msvc-160

Interestingly, all of the FTDI calls are now done with rust but the linker figures it all out. In that world, it looks something like
`cl /MD c_file.c rust.lib ftd2xx64.lib`. It works fine for me because it's a controlled environment and I can just hard code msvc paths, but I think this would likely end up in too much pain for something that has little demand.

2020-12-30 06:20 UTC, newAM approved these changes

2020-12-30 06:20 UTC, merged